import { Car, Booking } from './types';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    name: 'BMW M5 Competition',
    type: 'Luxury Sedan',
    category: 'Luxury',
    price: 245,
    rating: 4.9,
    host: 'Sixt Platinum Elite',
    hostAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBTSSeF5fUi8T-XTg6VmQG_xqn2qx25vIX0GHxyjRxt6F-3zuxhwlhxdSfnvnT9ULqMWAVNlmh1y69SFVEvVabFvLT6Jy0vb9jE4Q682pINnI4UgEC0o58T7R24AXpEkfz_kETNlzqDM99bebPBkpyUYQeOcQAkbzHEKDpCGFKK5fCwAlnNIP1LSc3ZCQC2sunGmvIK-2fjGufvytsKkbt6TW-H01WbYrEQD-ftIv0EbW1ZN8a3SP492VjrYPTqX94E_FrKQ3Rwmkzj',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKG5HSEcqE4WRJOXZbTlw3qkjhgDPj21bLvfTI-RRuYQKXl6x6OBdzWMSfV4-BUYcPRGeRsBqMoYjtxg-7CR7Om5DGcm5ifz-RJkS9sv4ld4ccHTeZS76Dj9Gd3pYh2LMmtfCKdC1RIcDLqzeclbnsb1Etq3kK9Soogs8Dtv3f7BS5Gm3cL76kJ5qL4adtVXeW_HOkK-oMCdceUiNMfZFNjzcmjNt-FSo2gZxpGguArPS_J1bbkLNJkKikRHFx2OQVHIvEeFxHg34J',
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Petrol',
    description: 'Ultimate Performance & Executive Comfort. The BMW M5 Competition combines track-ready performance with the luxury of a premium sedan.',
    features: ['GPS Navigation', 'Leather Seats', 'Sunroof', 'Bluetooth'],
    location: 'Beverly Hills, CA',
    isLimited: true
  },
  {
    id: '2',
    name: 'Porsche 911 Carrera S',
    type: 'Luxury Sport',
    category: 'Sports',
    price: 450,
    rating: 4.9,
    host: 'EliteDrive Premium',
    hostAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKNL488OKwRbzD7lH5CspGf4YiXVVHxB8PlqbfpB757gpvOEf6fdTAVuVVTpLqI3SYPcAWjGqGTVBlK2YLgub4G1gw2Fu4XKnRb9tD9ZsqCZyX1Zayft17X99-HKnWhy7wxMHUjNnVN4gWCmbX7UP4btGKW2nQkvihLbkPZhD0xCKQ8x62mze3RzmEJ4dnUBWdBTih1GWorOtJFdvGSrTRkLeWJIdHSCbNH60RnCiP617LlqBXwct-V2_rWv-2qO5pufetyGjYfy1q',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzPjN0_cGBV0yTARY-pyC9ISfuf9_o9natfX7_FM6-PZ0qTFibtnjegNzdM_Eo3vLQWXnCVSKWZoEGOLQgt3qZHGkwC7P7YtnDAU3bcb10a12p3zgrWlppi3I2Yd06RDv9UwHUj8Q4q8M0KJwBFE5MRlW2yzXMZpGx3CDsyIw99MxiVSLY-6D_YKDQU-MNiwSIgHh9-CaGS6P7Ad_6_D0yBvCYUgoGHgLpsHc2a0Rg4qq4KKHqBCM3_f7g3Q3o5ZSXv0dOXwCH22_W',
    seats: 4,
    transmission: 'Automatic',
    fuel: 'Petrol',
    description: 'Experience the legendary performance of the Porsche 911 Carrera S. This model features a twin-turbocharged flat-six engine that delivers 443 horsepower.',
    features: ['GPS Navigation', 'Leather Seats', 'Sunroof', 'Bluetooth'],
    location: 'Beverly Hills, CA'
  },
  {
    id: '3',
    name: 'Land Rover Defender',
    type: 'Luxury SUV',
    category: 'SUV',
    price: 180,
    rating: 4.8,
    host: 'Avis Luxury Collection',
    hostAvatar: 'https://picsum.photos/seed/host3/100/100',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0Y3gBu5Oobo5zrDhA14Of6z2CKDdOUC2C824eraLpzYSqx5Esd4r4SgrW5R5O_S3ZUGSnmFiP5fSQrp8EtJdg_6XUw3SCA-Ihs9D_y4c4CZnYPeI1SMHZekr0VkTCdmxYZNwz7Va0edvy0EitNdAJL3opn7_GrMdfF4yhjbdV5Zx6ZgtRitIxcdWCdsLXEEmW-jcl5-nVyEO7EMn0eA92FDtdzhX4Q-DkxanO_VqOQ3sUgEjsJt_SmQm1fiBecyE9mp8WGGy1xQ-b',
    seats: 7,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    description: 'Rugged capability meets modern luxury. The Land Rover Defender is ready for any adventure.',
    features: ['GPS Navigation', 'Sunroof', 'Bluetooth'],
    location: 'Malibu, CA'
  },
  {
    id: '4',
    name: 'Tesla Model S Plaid',
    type: 'Electric Sedan',
    category: 'Electric',
    price: 210,
    rating: 5.0,
    host: 'Local Rent Premium',
    hostAvatar: 'https://picsum.photos/seed/host4/100/100',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQmzyBogfw-F-x42WHKx0Ba0QfY17Js--cOol7gVLyMlKjhrZYQUKwzWgjuBjCmDhrb-GPLG86FBhe0eUzOu5y6EpiRUQrkJWjAYleoyKH6YIbgePI0asPaqbnMp82Y1TLR5e1VkJF_t_jPvuOjPhrNIBz9MRbAazm65jvRW7-lvpSGK5L9okbNWzMt_uHhupdKMDXsffx7Nt_Hg69CDNdEp5Fo-hOx78UtUEfCGgpb3uBWL3GM6hysNplkakZTvsJ5Reg4Kca1cfX',
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Electric',
    description: 'The quickest accelerating car in production today. 0-60 mph in 1.99s with Autopilot, premium sound and a stunning panoramic sunroof.',
    features: ['GPS Navigation', 'Leather Seats', 'Sunroof', 'Bluetooth'],
    location: 'Palo Alto, CA'
  },
  {
    id: '5',
    name: 'Toyota Corolla',
    type: 'Economy Sedan',
    category: 'Economy',
    price: 55,
    rating: 4.5,
    host: 'Budget Rentals',
    hostAvatar: 'https://picsum.photos/seed/host5/100/100',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Petrol',
    description: 'Reliable, fuel-efficient and comfortable. The Toyota Corolla is the perfect everyday city car for short trips and business travel.',
    features: ['GPS Navigation', 'Bluetooth'],
    location: 'Los Angeles, CA'
  },
  {
    id: '6',
    name: 'Honda Civic',
    type: 'Economy Compact',
    category: 'Economy',
    price: 65,
    rating: 4.4,
    host: 'EasyRide',
    hostAvatar: 'https://picsum.photos/seed/host6/100/100',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    seats: 5,
    transmission: 'Manual',
    fuel: 'Petrol',
    description: 'The Honda Civic is a compact car that strikes the perfect balance between efficiency and driving fun, ideal for city and highway.',
    features: ['Bluetooth', 'GPS Navigation'],
    location: 'Santa Monica, CA'
  }
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    carId: '2',
    carName: 'Porsche 911 Carrera S',
    carImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiHXR3lEUBTnnwuteYnBXOSycmgwmAcFJbKZbOXhcJb1i1w8w5hx_1CkkyJYsS_bh-vKOzHLgFy-gMLoqg3XEtQIeomIeyLuPAsdYzNYPUOex80PYwXQxZIvaIQtdAKauOrzI0ruqDhFrCnu71hphzEyr3VL9Ya2byfNoOH422uL5YOLv0TMKTIG9307eSsgmdo8IMcRi8sxvto0627qWo06tdsaC05-ysulPS-Q91f4rFQCPXZ_VX02dhWX6htAR5fzUZaDb-3SGI',
    confirmationNumber: '#ED-82910',
    totalPrice: 1240.00,
    pickupDate: 'Oct 12, 2023',
    returnDate: 'Oct 15, 2023',
    status: 'Upcoming'
  },
  {
    id: 'b2',
    carId: '1',
    carName: 'BMW M5 Competition',
    carImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAs9WC9qZaTcGM3dqb7li1JtTjfODr1A0zkq1-2gSXWzV-k0BYpN1WOO5IgtsVl59teNIoXFNzo8O0AXVkSTqxC1cmZWblVfeEx-WvMwUOykIikJrT5Djsk4Rb_gpr7ZV7phhMGDoSvJHFbJA-CbfL0djYwRUJ8Cv25L0IA12G0atyYjekeOHlZH6wXka4BX8aBaB12GUFVVSZOluSImVlvMi50gOZF0HGBZMCT-Xu3G1z5wuVbT3PLUlnW6wDKRJwUVW5wmQ1iu5Hd',
    confirmationNumber: '#ED-77124',
    totalPrice: 890.00,
    pickupDate: 'Sep 20, 2023',
    returnDate: 'Sep 22, 2023',
    status: 'Completed'
  },
  {
    id: 'b3',
    carId: '5',
    carName: 'Ferrari Roma',
    carImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWAYzQPRwx_qeePZWLY1FcfiO0t8UVkleTMaSi1BsNZ9RAVK2DWLYnGJViwZJZ39YIkTI-GREsKIdol458Avb1AYVp0HOyVl53PrC5AdGf2_Olybo-WCKiiu3nC5MGxwSdtmcp0krb6Nc1uE1nzUcKcnRjwJblYc0AyZDyz02gD8fY4SK1tRekUejBdinl7cj_Lhip4sHp_2XACLpwWZ4fV2HY9R6LFCvqnIRVOUraXOdE67aofdo9knUy7F8Kn0KN9UmIMeVkuxgR',
    confirmationNumber: '#ED-65441',
    totalPrice: 2100.00,
    pickupDate: 'Aug 05, 2023',
    returnDate: 'Aug 07, 2023',
    status: 'Cancelled',
    isRefunded: true
  }
];